In [30]:
years = list(range(1992,2022))
import requests
from bs4 import BeautifulSoup
from io import StringIO

In [32]:
url_template = "https://www.basketball-reference.com/awards/awards_{}.html"

In [39]:

for year in years: 
    url = url_template.format(year) 
    data = requests.get(url)

    with open("NBA_Project/mvps/{}.html".format(year), "w+") as file:
        file.write(data.text)

In [6]:
with open ("NBA_Project/mvps/1992.html") as file: 
    page = file.read()

In [7]:
soup = BeautifulSoup(page, "html.parser")

In [8]:
soup.find("tr", class_="over_header").decompose()

In [9]:
mvp_tables = soup.find(id = "mvp")

In [7]:
mvp_1992 = pd.read_html(str(mvp_tables))[0]

/var/folders/4k/s8gv3ln52dzc5xp0dq85vdq80000gn/T/ipykernel_34574/3505721023.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  mvp_1992 = pd.read_html(str(mvp_tables))[0]

In [8]:
mvp_1992

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,28,CHI,80,900,960,0.938,80,38.8,30.1,6.4,6.1,2.3,0.9,0.519,0.270,0.832,17.7,0.274
1,2,Clyde Drexler,29,POR,12,561,960,0.584,76,36.2,25.0,6.6,6.7,1.8,0.9,0.470,0.337,0.794,12.8,0.223
2,3,David Robinson,26,SAS,2,337,960,0.351,68,37.7,23.2,12.2,2.7,2.3,4.5,0.551,0.125,0.701,13.9,0.260
3,4,Karl Malone,28,UTA,1,262,960,0.273,81,37.7,28.0,11.2,3.0,1.3,0.6,0.526,0.176,0.778,15.1,0.237
4,5,Patrick Ewing,29,NYK,0,100,960,0.104,82,38.4,24.0,11.2,1.9,1.1,3.0,0.522,0.167,0.738,13.0,0.198
5,6,Chris Mullin,28,GSW,0,81,960,0.084,81,41.3,25.6,5.6,3.5,2.1,0.8,0.524,0.366,0.833,10.8,0.155
6,7,Mark Price,27,CLE,0,66,960,0.069,72,29.7,17.3,2.4,7.4,1.3,0.2,0.488,0.387,0.947,9.1,0.205
7,8,Tim Hardaway,25,GSW,0,64,960,0.067,81,41.1,23.4,3.8,10.0,2.0,0.2,0.461,0.338,0.766,9.2,0.132
8,9,Scottie Pippen,26,CHI,1,32,960,0.033,82,38.6,21.0,7.7,7.0,1.9,1.1,0.506,0.200,0.760,12.7,0.192
9,10,Dennis Rodman,30,DET,0,26,960,0.027,82,40.3,9.8,18.7,2.3,0.8,0.9,0.539,0.317,0.600,12.6,0.183
10,11,Brad Daugherty,26,CLE,0,24,960,0.025,73,36.2,21.5,10.4,3.6,0.9,1.1,0.570,0.000,0.777,11.7,0.213
11,12T,Charles Barkley,28,PHI,0,18,960,0.019,75,38.4,23.1,11.1,4.1,1.8,0.6,0.552,0.234,0.695,12.3,0.205
12,12T,John Stockton,29,UTA,0,18,960,0.019,82,36.6,15.8,3.3,13.7,3.0,0.3,0.482,0.407,0.842,13.4,0.215
13,14,Larry Bird,35,BOS,0,3,960,0.003,45,36.9,20.2,9.6,6.8,0.9,0.7,0.466,0.406,0.926,5.5,0.159
14,15,Kevin Johnson,25,PHO,0,2,960,0.002,78,37.2,19.7,3.7,10.7,1.5,0.3,0.479,0.217,0.807,10.0,0.165
15,16T,Danny Manning,25,LAC,0,1,960,0.001,82,35.4,19.3,6.9,3.5,1.6,1.5,0.542,0.000,0.725,9.8,0.162
16,16T,Detlef Schrempf,29,IND,0,1,960,0.001,80,32.6,17.3,9.6,3.9,0.8,0.5,0.536,0.324,0.828,9.8,0.181

In [24]:
dfs= []
for year in years:
    with open ("NBA_Project/mvps/{}.html".format(year)) as file: 
        page = file.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find("tr", class_="over_header").decompose()
    mvp_tables = soup.find(id = "mvp")
    mvp = pd.read_html(StringIO(str(mvp_tables)))[0]
    mvp["Year"] = year

    dfs.append(mvp)

In [26]:
mvps = pd.concat(dfs)
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,28,CHI,80,900,960,0.938,80,38.8,...,6.4,6.1,2.3,0.9,0.519,0.270,0.832,17.7,0.274,1992
1,2,Clyde Drexler,29,POR,12,561,960,0.584,76,36.2,...,6.6,6.7,1.8,0.9,0.470,0.337,0.794,12.8,0.223,1992
2,3,David Robinson,26,SAS,2,337,960,0.351,68,37.7,...,12.2,2.7,2.3,4.5,0.551,0.125,0.701,13.9,0.260,1992
3,4,Karl Malone,28,UTA,1,262,960,0.273,81,37.7,...,11.2,3.0,1.3,0.6,0.526,0.176,0.778,15.1,0.237,1992
4,5,Patrick Ewing,29,NYK,0,100,960,0.104,82,38.4,...,11.2,1.9,1.1,3.0,0.522,0.167,0.738,13.0,0.198,1992

In [27]:
mvps.to_csv("mvps.csv")

In [32]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

url = player_stats_url.format(1992)
data= requests.get(url)
with open("NBA_Project/player/1992.html", "w+") as file: 
    file.write(data.text)

In [2]:
!pip install selenium

Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (4.29.0)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.10)
Requirement already satisfied: outcome in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: exceptiongroup in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.2)
Requirement already satisfied: wsproto>=0.14 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
xattr -d com.apple.quartantine Downloads/chrome-mac-arm64

SyntaxError: invalid syntax (2118401157.py, line 1)